# Generated by Django 3.0.6 on 2020-05-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('attempts', models.IntegerField()),
                ('attempt_time', models.TimeField()),
            ],
        ),
    ]
