# Generated by Django 3.0.6 on 2020-05-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='img',
            field=models.ImageField(default='blog-image.jpg', upload_to='images'),
        ),
    ]
