# Generated by Django 3.0.6 on 2020-06-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_blogs_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
